name: CI

on:
  pull_request:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Check
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Build Project
        run: bun run build

      - name: Lint
        run: bun run lint